import type { Artifact, Session, Todo } from './types'

export const ME = '陈华明'

export const sessions: Session[] = [
  { id: 's1', title: '积压差旅报销过一遍', time: '今天 14:12', status: 'idle' },
  { id: 's2', title: '供应商引入·技术评审', time: '今天 11:03', status: 'idle' },
  { id: 's3', title: '会议室冲突协调', time: '昨天 18:40', status: 'idle' },
]

export const initialTodos: Todo[] = [
  {
    id: 't1',
    title: '差旅费报销 · 主管审批',
    subtitle: '张工 · 上海出差 · 发票 3 张',
    domain: '报销',
    pri: 'high',
    due: '今天 18:00',
    agent: true,
    relation: 'mine_todo',
    state: 'pending',
    amount: '¥4,860',
    app: 'W3',
    url: 'https://w3.internal/approve/EXP-2026-1042',
    flow: {
      nodes: [
        { label: '提单', status: 'done', actor: '张工', date: '09-28' },
        { label: '主管审批', status: 'current', actor: '我', date: '10-06' },
        { label: '财务复核', status: 'todo', actor: '财务部' },
        { label: '出纳支付', status: 'todo', actor: '出纳' },
      ],
    },
    reviewFlags: { suggestAgree: true },
  },
  {
    id: 't2',
    title: '差旅费报销 · 主管审批',
    subtitle: '李娜 · 深圳客户拜访',
    domain: '报销',
    pri: 'mid',
    due: '明天 12:00',
    agent: true,
    relation: 'mine_todo',
    state: 'pending',
    amount: '¥12,400',
    app: 'W3',
    url: 'https://w3.internal/approve/EXP-2026-1108',
    flow: {
      nodes: [
        { label: '提单', status: 'done', actor: '李娜', date: '10-02' },
        { label: '主管审批', status: 'current', actor: '我' },
        { label: '财务复核', status: 'todo', actor: '财务部' },
      ],
    },
    reviewFlags: { needReview: true, reason: '金额超预算 ¥2,400，发票合计与单据差 ¥180' },
  },
  {
    id: 't3',
    title: '差旅费报销 · 主管审批',
    subtitle: '王凯 · 北京培训',
    domain: '报销',
    pri: 'low',
    due: '10-08',
    agent: true,
    relation: 'mine_todo',
    state: 'pending',
    amount: '¥2,160',
    app: 'W3',
    url: 'https://w3.internal/approve/EXP-2026-1115',
    flow: {
      nodes: [
        { label: '提单', status: 'done', actor: '王凯', date: '10-04' },
        { label: '主管审批', status: 'current', actor: '我' },
        { label: '财务复核', status: 'todo', actor: '财务部' },
      ],
    },
    reviewFlags: { suggestAgree: true },
  },
  {
    id: 't4',
    title: '供应商引入采购 · 技术评审',
    subtitle: '星河科技 · 服务器配件',
    domain: '采购',
    pri: 'high',
    due: '今天 17:30',
    agent: true,
    relation: 'mine_todo',
    state: 'pending',
    app: 'W3',
    url: 'https://w3.internal/flow/PO-INTRO-8821',
    flow: {
      nodes: [
        { label: '立项申请', status: 'done', actor: '王五', date: '09-18', note: '预算已批' },
        { label: '商务谈判', status: 'done', actor: '李四', date: '09-26' },
        { label: '技术评审', status: 'current', actor: '我', date: '10-06' },
        { label: '法务审核', status: 'todo', actor: '法务部' },
        { label: '归档', status: 'todo', actor: '采购部' },
      ],
      context: {
        chats: [
          {
            title: '供应商引入-技术组',
            excerpt: '张工：接口协议与现网兼容，建议有条件通过。',
            time: '昨天 16:21',
          },
          {
            title: '供应商引入-技术组',
            excerpt: '赵工：交付周期偏紧，需补充备件清单。',
            time: '昨天 17:04',
          },
        ],
        mails: [
          {
            title: '评分表-星河科技.xlsx',
            from: '采购助理 · 周敏',
            excerpt: '三位评委评分已汇总，平均 82.6 分。',
            time: '今天 09:12',
          },
        ],
        meetings: [
          {
            title: '技术评审会纪要',
            excerpt: '结论倾向：有条件通过；待补安全扫描报告。',
            time: '10-05 14:00',
          },
        ],
      },
    },
  },
  {
    id: 't5',
    title: '任职资格答辩 · 材料规范性审核',
    subtitle: 'P6 晋升 · 刘洋',
    domain: 'HR',
    pri: 'mid',
    due: '10-09',
    agent: true,
    relation: 'mine_todo',
    state: 'pending',
    app: 'W3',
    url: 'https://w3.internal/hr/qualify/LY-2026',
    flow: {
      nodes: [
        { label: '材料提交', status: 'done', actor: '刘洋', date: '10-01' },
        { label: '材料规范性审核', status: 'current', actor: '我' },
        { label: '答辩安排', status: 'todo', actor: 'HR 专员' },
      ],
    },
  },
  {
    id: 't6',
    title: '会议室确认 · 行政确认',
    subtitle: 'A3-12 · 周四 14:00 评审会',
    domain: '行政',
    pri: 'low',
    due: '明天 10:00',
    agent: true,
    relation: 'mine_todo',
    state: 'pending',
    app: '行政门户',
    url: 'https://office.internal/room/A3-12',
  },
  {
    id: 't9',
    title: '整理本周周报要点',
    subtitle: '普通任务 · 可手动勾选完成',
    domain: '项目协作',
    pri: 'low',
    due: '周五 18:00',
    agent: true,
    relation: 'mine_todo',
    state: 'pending',
    app: '工作台',
    url: '',
    kind: 'simple',
  },
  {
    id: 't7',
    title: '供应商引入采购 · 法务审核',
    subtitle: '我发起 · 当前处理人：法务部',
    domain: '采购',
    pri: 'mid',
    due: '跟踪中',
    agent: false,
    relation: 'mine_initiated',
    state: 'pending',
    app: 'eBuy',
    url: 'https://ebuy.internal/po/INTRO-7710',
    flow: {
      nodes: [
        { label: '立项申请', status: 'done', actor: '王五', date: '09-12' },
        { label: '商务谈判', status: 'done', actor: '李四', date: '09-20' },
        { label: '技术评审', status: 'done', actor: '我', date: '09-29' },
        { label: '法务审核', status: 'current', actor: '法务部' },
        { label: '归档', status: 'todo', actor: '采购部' },
      ],
    },
  },
  {
    id: 't8',
    title: '差旅费报销 · 财务复核',
    subtitle: '我发起 · 当前处理人：财务部',
    domain: '报销',
    pri: 'low',
    due: '跟踪中',
    agent: false,
    relation: 'mine_initiated',
    state: 'pending',
    app: '费控',
    url: 'https://w3.internal/expense/MY-0922',
    flow: {
      nodes: [
        { label: '提单', status: 'done', actor: '我', date: '09-22' },
        { label: '主管审批', status: 'done', actor: '林总监', date: '09-23' },
        { label: '财务复核', status: 'current', actor: '财务部' },
      ],
    },
  },
]

export const initialArchived: Todo[] = [
  {
    id: 'a1',
    title: '加班餐补 · 主管审批',
    subtitle: '9 月批次 · 12 人',
    domain: '报销',
    pri: 'low',
    due: '已完成',
    agent: true,
    relation: 'mine_todo',
    state: 'done',
    execBy: 'mix',
    amount: '¥1,680',
    app: 'W3',
    url: '',
  },
  {
    id: 'a2',
    title: '培训报名 · 部门确认',
    subtitle: 'AI 产品工作坊',
    domain: 'HR',
    pri: 'mid',
    due: '已完成',
    agent: false,
    relation: 'mine_todo',
    state: 'done',
    execBy: 'human',
    app: 'W3',
    url: '',
  },
  {
    id: 'a3',
    title: '合同续签提醒生成',
    subtitle: 'Agent 自动起草催办邮件',
    domain: '行政',
    pri: 'low',
    due: '已完成',
    agent: true,
    relation: 'mine_todo',
    state: 'done',
    execBy: 'agent',
    app: '工作台',
    url: '',
  },
]

export const initialArtifacts: Artifact[] = [
  {
    id: 'f1',
    type: 'xls',
    name: '差旅报销对照表.xlsx',
    sub: '今天 14:18 · 3 条比对',
    kind: 'doc',
    source: 'agent',
    status: 'done',
    session: '积压差旅报销过一遍',
    pages: '1 页',
    preview:
      '条目\t发票合计\t单据金额\t结论\n张工上海出差\t4860\t4860\t建议同意\n李娜深圳拜访\t12220\t12400\t需人工复核\n王凯北京培训\t2160\t2160\t建议同意',
  },
  {
    id: 'f2',
    type: 'doc',
    name: '技术评审意见草稿.docx',
    sub: '今天 11:20',
    kind: 'doc',
    source: 'dialogue',
    status: 'done',
    session: '积压差旅报销过一遍',
    pages: '2 页',
    preview:
      '评审结论（草稿）\n\n综合三位评委意见，建议「有条件通过」。\n1. 接口协议与现网兼容（张工）\n2. 交付周期偏紧，需补充备件清单（赵工）\n3. 安全扫描报告待补（评审会纪要）\n\n平均分 82.6。提交前请人工确认。',
  },
  {
    id: 'f3',
    type: 'html',
    name: '评审节点进度.html',
    sub: '今天 11:22',
    kind: 'code',
    source: 'flow',
    status: 'done',
    session: '积压差旅报销过一遍',
    pages: '网页',
    preview: '<h2>供应商引入采购</h2><p>当前节点：技术评审（你）</p><p>下一节点：法务审核</p>',
  },
  {
    id: 'f4',
    type: 'ppt',
    name: '本周待办积压简报.pptx',
    sub: '昨天',
    kind: 'doc',
    source: 'dialogue',
    status: 'done',
    session: '供应商引入·技术评审',
    pages: '6 页',
    preview: '封面：本周待办积压简报\nP2 报销积压 8 条\nP3 采购评审 2 条超期风险\nP4 建议批量处理路径',
  },
]

export const appShortcuts = [
  { id: 'w3', name: 'W3 审批', url: 'https://w3.internal/todo', desc: '待我审批 / 我的申请' },
  { id: 'ebuy', name: 'eBuy 采购', url: 'https://ebuy.internal', desc: '供应商与订单' },
  { id: 'fee', name: '费控报销', url: 'https://fee.internal', desc: '发票与单据' },
  { id: 'oa', name: '行政门户', url: 'https://office.internal', desc: '会议室 / 资源' },
]

export const suggestions = [
  '帮我把积压的差旅报销都过一遍',
  '协同处理供应商引入的技术评审',
  '看看我发起的流程卡在哪',
  '把这个页面里待审批的条目核对一下',
  '刚刚核对出的差异有哪些',
]

export const sessionSeeds: Record<string, { role: 'user' | 'agent' | 'system'; text: string; time: string }[]> = {
  s1: [],
  s2: [
    { role: 'user', text: '帮我看一下星河科技的技术评审卡在哪', time: '11:03:12' },
    { role: 'agent', text: '当前节点是技术评审，负责人是你。点协同处理后我会抽取群聊与评分表，停在提交结论前。', time: '11:03:20' },
  ],
  s3: [
    { role: 'user', text: '周四评审会和另一个会冲突了', time: '昨天 18:40' },
    { role: 'agent', text: '行政确认待办在流程活动里。会议室确认是你的待办，可协同处理；冲突协调我只能起草提醒，改期需你确认。', time: '昨天 18:41' },
  ],
}
